stages:
  - test
  - image
  - release

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

default:
  image:
    name: $CI_REGISTRY/images/goreleaser:stable
    entrypoint: [""]

test:
  stage: test
  script:
    - gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

build image:
  stage: image
  trigger:
    strategy: mirror
    include:
      - component: $CI_SERVER_FQDN/oaklab/ci-templates/hadolint@11
      - component: $CI_SERVER_FQDN/oaklab/ci-templates/oci-publish@11
        inputs:
          licenses: MIT
          platforms:
            - linux/amd64
            - linux/arm64
          registry-cache: true

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    # Provide so that goreleaser uses the job token
    GITLAB_TOKEN: $CI_JOB_TOKEN
  script:
    - goreleaser release --clean
